version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
    groups:
      testing:
        patterns:
          - "pytest*"
          - "coverage*"
      linting:
        patterns:
          - "ruff*"
          - "black*"
          - "mypy*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:30"
    open-pull-requests-limit: 10