# pysearch example configuration (copy to configs/config.local.toml and modify as needed)
[search]
paths = ["./src"]
include = ["**/*.py"]
exclude = ["**/.venv/**", "**/.git/**", "**/__pycache__/**", "**/build/**", "**/dist/**"]
context = 2
output_format = "text"
enable_docstrings = true
enable_comments = true
enable_strings = false

[filters]
func_name = ""
class_name = ""
decorator = ""
imported = ""

[ranking]
# Example: weights for different signals (illustrative, actual implementation may vary)
text_weight = 1.0
ast_weight = 2.0
semantic_weight = 1.0