# pysearch 示例配置（可复制为 configs/config.local.toml 并按需覆盖）
[search]
paths = ["./src"]
include = ["**/*.py"]
exclude = ["**/.venv/**", "**/.git/**", "**/__pycache__/**", "**/build/**", "**/dist/**"]
context = 2
output_format = "text"
enable_docstrings = true
enable_comments = true
enable_strings = false

[filters]
func_name = ""
class_name = ""
decorator = ""
imported = ""

[ranking]
# 示例：各信号的权重（仅示意，具体以实现为准）
text_weight = 1.0
ast_weight = 2.0
semantic_weight = 1.0